{ modulesPath, ... }:
{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  # Placeholder — overwritten by nixos-generate-config during initial deploy.
  # Do not edit this file directly.
  boot.initrd.availableKernelModules = [
    "virtio_pci"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];

  nixpkgs.hostPlatform = "aarch64-linux";
}
